name: Test using docker

on:
  # Runs on pushes targeting the default branch
  push:
    branches: ["master"]

jobs:
# Single deploy job since we're just deploying
  Test_build_samples:
    strategy:
      matrix:
        samples_to_test:
          - samples/template_subghz
          - samples/template_ble
          - samples/sensor_monitoring
          - samples/sid_dut

    runs-on: ubuntu-latest
    container:
      image: nordicplayground/nrfconnect-sdk:main
      options: --cpus 2

    steps:
      - name: install gcc-multilib
        run: apt install -y gcc-multilib

      - name: Pull sidewalk
        run: git clone https://github.com/nrfconnect/sdk-sidewalk /home/runner/siewalk

      - name: link project
        run: cp -r /home/runner/siewalk  /workdir/sidewalk

      - name: Reconfigure west
        run: cd /workdir; west config manifest.path sidewalk; west update -n -o=--depth=1

      - name: twister build samples 
        run: /workdir/zephyr/scripts/twister --testsuite-root /workdir/sidewalk/${{ matrix.samples_to_test }} --no-clean --show-footprint --footprint-from-buildlog -vvv --build-only
      
      - name: Upload build artifacts
        uses: actions/upload-artifact@v3
        with:
          name: ${{ github.sha }}-${{ matrix.samples_to_test }}
          path: twister-out

  Run_Tests: 
    strategy:
      matrix:
        samples_to_test:
          - tests/functional
          - tests/manual
          - tests/unit_tests
          - tests/validation

    runs-on: ubuntu-latest
    container:
      image: nordicplayground/nrfconnect-sdk:main
      options: --cpus 2

    steps:
      - name: install gcc-multilib
        run: apt install -y gcc-multilib

      - name: Pull sidewalk
        run: git clone https://github.com/nrfconnect/sdk-sidewalk /home/runner/siewalk

      - name: link project
        run: cp -r /home/runner/siewalk  /workdir/sidewalk

      - name: Reconfigure west
        run: cd /workdir; west config manifest.path sidewalk; west update -n -o=--depth=1

      - name: twister build and run x86 tests 
        run: /workdir/zephyr/scripts/twister --testsuite-root /workdir/sidewalk/${{ matrix.samples_to_test }}  --no-clean -vvv
