name: Test using docker

on:
  # Runs on pushes targeting the default branch
  push:
    branches: ["master"]

jobs:
# Single deploy job since we're just deploying
  Build_zephyr_sample:
    runs-on: ubuntu-latest
    container:
      image: nordicplayground/nrfconnect-sdk:main

    steps:
      - name: Pull sidewalk
        run: git clone https://github.com/nrfconnect/sdk-sidewalk /home/runner/siewalk

      - name: link project
        run: cp -r /home/runner/siewalk  /workdir/sidewalk

      - name: Reconfigure west
        run: cd /workdir; west config manifest.path sidewalk; west update -n -o=--depth=1

      - name: Build sample
        run: west build /workdir/sidewalk/samples/sid_dut -b nrf52840dk_nrf52840
    
      - name: twister build samples 
        run: /workdir/zephyr/scripts/twister -T /workdir/zephyr/sidewalk --build-only --no-clean --show-footprint --footprint-from-buildlog
      
      - name: archive artifacts
        run: zip ${{ github.sha }}-twister-output.zip twister-output

      - name: twister run unit tests
        run: /workdir/zephyr/scripts/twister -T /workdir/zephyr/sidewalk/tests/unit_tests --no-clean

